services:
    gl.sql_server_service:
        class: garinlu\SQLServerBundle\Utils\SQLServerService
        arguments:
            - "%sqlserver.serverName%"
            - "%sqlserver.UID%"
            - "%sqlserver.PWD%"
